### ISSUE TITLE
Wrong pasteo token cause runtime panic

### ISSUE THREAD

**Issue by techport-om** [rrrodzilla/rusty_paseto#29]
**Describe the bug**
While testing i discovered a case where the library will panic instead of throwing an error. Explicitly while attempting a wrong token "v4.local.1234". 

The error is 
```
rusty_paseto-0.6.0/src/core/paseto.rs:766:47:
range end index 32 out of range for slice of length 3
```

**To Reproduce**
just try to decrypt "v4.local.1234"

**Expected behavior**
i was expecting to catch the error same as other errors. 

**Additional context**
I think this problem could be solved by checking the length of the third part. I am interested to create a PR for this as first contribution.

**Comment by rrrodzilla** [comment]
I was unable to reproduce this. I wrote a test to check for this but it provides an error in the result as expected. If you've got an example I can repro from I'll be happy to look into it again.
