### ISSUE TITLE
Bumping dependencies

### ISSUE THREAD

**Issue by LecrisUT** [rrrodzilla/rusty_paseto#36]
When trying to package this for Fedora, I've encountered incompatible rust dependencies with the lastest crates:
- `blake2 = "^0.9.2"`
- `chacha20 = "0.8.1"`

Any plans on bumping and testing the dependencies?

**Comment by rrrodzilla** [comment]
v0.7.0 has been published to crates.io
Thanks!

**Comment by LecrisUT** [comment]
Quick issue, it seems `core/error.rs` does not compile properly:
```
rror[E0119]: conflicting implementations of trait `From<ed25519_dalek::ed25519::Error>` for type `core::error::PasetoError`
 --> src/core/error.rs:5:17
  |
5 | #[derive(Debug, Error)]
  |                 ^^^^^
  |                 |
  |                 first implementation here
  |                 conflicting implementation for `core::error::PasetoError`
  |
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Encountered it in `paserk`, and can be reproduced if you include a builder with `--all-features`

**Comment by LecrisUT** [comment]
I've managed to narrow down the issue to:
https://github.com/rrrodzilla/rusty_paseto/blob/448738a4bdb1087e5c64b528b6891550538f7ebb/src/core/error.rs#L41-L48

If I remove that section, the compilation manages to finish

I don't have the expertise to know what a proper patch for this should be

**Comment by rrrodzilla** [comment]
What's the use case for compiling with all features enabled?

For PASETO, you should pick one protocol and version to use throughout your application. The crate uses conditional compilation, building different versions based on the feature you choose.

Compiling with all features causes conflicts because it includes multiple copies of types with the same names (e.g., the `Error` type), which the compiler won't allow. Fixing this particular error will only lead to more issues.

It's possible to generate unique names based on the version and protocol, but I'm curious about the need for this approach since it's not a typical use case.

**Comment by LecrisUT** [comment]
> What's the use case for compiling with all features enabled?

For `rusty_paserk` the issue is that it provides compatibility for both [`v3` and `v4`](https://github.com/conradludgate/rusty-paserk/blob/9b033086824821e91c41793cfe2149d3bb8a465a/Cargo.toml#L20-L41) so it's rather hard to compile it since it would still hit this issue. For the endgoal (`atuin`) only the `v4` is used, so in principle it would be possible to just not packager `rusty_paserk/v3` but I'm not sure if down the line when another project needs to be packaged that would use `rusty_paserk/v3`

**Comment by rrrodzilla** [comment]
That makes things clear. I didn't write `rusty_paserk`. The solution is for me to finish adding PASERK functionality, which I'd been putting off since no one has asked for it. I should be able to add v4 pretty quickly.

I've opened #38 for tracking.

Thanks!

**Comment by rrrodzilla** [comment]
Another option is to reach out to them and see if they'll update their crate to support what you're trying to do. I wasn't involved in creating that crate.

**Comment by conradludgate** [comment]
I will update rusty_paserk shortly. Thanks for the notice
