### ISSUE TITLE
Invalid JSON payload when using CustomClaims with T that serialize to an JSON object

### ISSUE THREAD

**Issue by xbb** [rrrodzilla/rusty_paseto#39]
**Describe the bug**
If you pass a serializable struct to `CustomClaims` the builder will generate an invalid JSON payload due to the trimming of multiple object delimiters.

The builder will still build a token successfully, but the validation will fail with a JSON error.

See my quick fix attempt here: https://github.com/xbb/rusty_paseto/commit/00b1a9075e94f472e6c48b56f800b571847308e7

**Comment by rrrodzilla** [comment]
Thanks I'll have a look

**Comment by rrrodzilla** [comment]
Closing issue #39 as it has been addressed in [PR #40](https://github.com/rrrodzilla/rusty_paseto/pull/40). Please refer to the closing notes in the PR for a description of the fix. Credit and thanks to @xbb for reporting the issue and offering a suggestion on the fix.
